model: BERT4Rec
hidden_size: 512
inner_size: 2048
num_hidden_layers: 4
num_attention_heads: 8
hidden_dropout_prob: 0.1
attn_dropout_prob: 0.1
mask_ratio: 0.2
hidden_act: gelu
layer_norm_eps: 1e-12
max_seq_length: 100
learning_rate: 1e-5

# Параметры для работы с признаками
feature_fusion: true  # Включаем механизм объединения признаков
numerical_projection_dropout: 0.1  # Dropout для числовых признаков
categorical_embedding_size: 512  # Размерность эмбеддингов категориальных признаков