model: SASRec
hidden_size: 256
inner_size: 512
num_hidden_layers: 6
num_attention_heads: 4
hidden_dropout_prob: 0.1
attn_dropout_prob: 0.1
hidden_act: gelu
layer_norm_eps: 1e-12
max_seq_length: 50
learning_rate: 0.001 